### ISSUE TITLE
Implement a Better Conversion Method for JSON to CSV

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/json-csv#1]
Currently, it is assumed that each object shares the same properties while converting [JSON to CSV](https://github.com/ozdemirburak/json-csv/blob/master/src/File/Json.php). So if one object has a property that the other one does not have, then it becomes a major problem.

So one should implement a better conversion method where it would not fail with objects that do not share the same properties.

Example Input:

```json
[
  {
    "x": 0,
    "y": 1
  },
  {
    "y": 0,
    "z": 0
  }
]
```

Output: (Wrong)

**x**|**y**
:-----:|:-----:
0|1
0|0

Expected Output: (True)

**x**|**y**|**z**
:-----:|:-----:|-----:
0|1|null
null|0|0

**Comment by martinsustek** [comment]
Hello, do you like this #2 ?
