### ISSUE TITLE
Can't convert JSON file

### ISSUE THREAD

**Issue by SmashScharrer** [ozdemirburak/json-csv#14]
Hey man ! ✋ 

I used your library for my work to convert some JSON files to CSV but for some of this files, I have an arror message like this : 
![image](https://user-images.githubusercontent.com/35690812/105337000-34b1d580-5bda-11eb-9dd8-7ed0dbc6ccb6.png)

Do you have a answer to this problem ?

Thank you ^^

**Comment by ozdemirburak** [comment]
Well, it is hard to say something without seeing the data. Probably, you are trying to convert a not-valid or empty JSON file.

**Comment by SmashScharrer** [comment]
Sorry i can show you this file because there are a lot of private data (enterprise data...). I have found and another solution. Thanks ^^
