### ISSUE TITLE
Delimiter

### ISSUE THREAD

**Issue by TechOverflow** [ozdemirburak/json-csv#7]
Hi!
I would like to know if there's a way to set the delimiter to `;` (Excel csv).
When I set `'delimiter' => ';',` instead of `'delimiter' => ',',` in Csv.php, I get false output.
Is there a solution to this?

Edit: In some Windows localizations, a comma is used for the currency decimal, so Windows sets the list separator to `;`.

Cheers!

**Comment by ozdemirburak** [comment]
Hi, you set the delimiter like below right?
```php
$csv->setConversionKey('delimiter', ';');
```
Can you share an example CSV string/file so that I can have a look.

Thanks.

**Comment by TechOverflow** [comment]
When I re-save the original file like this in CSV Converter, it works fine. I have no idea what's different about the Excel export.

<img width="835" alt="test" src="https://user-images.githubusercontent.com/40919041/48827377-62d2cb00-ed6d-11e8-9dd2-c85a592e598d.png">

**Comment by TechOverflow** [comment]
The issue was indeed with the foreign characters. When saving a csv in Excel, the file then needs to be opened in Notepad and saved as UTF-8 encoded, since Excel doesn't have this option.

**Comment by ozdemirburak** [comment]
I am closing this but you can reopen it if you have an example file with the foreign characters, so that I can have a look? Thanks again.
